apiVersion: v1
kind: Pod
metadata:
  name: sdk
spec:
  containers:
  - name: sdk
    image:  google/cloud-sdk

    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    
    volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}

