apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: python-app
          image: mohmadsabri/pythonapp:v1
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-service.deployment-poool.svc.cluster.local
